### ISSUE TITLE
Why the custom types? 

### ISSUE THREAD

**Issue by morganhein** [leaanthony/u#1]
I recently created a similar maybe/monad/optional type library like yourself:

https://github.com/morganhein/mo/blob/main/maybe.go

I'm trying to understand why you're creating custom types in your library? 

My question is 100% trying to understand if there's something i'm missing, but I don't see a reason to include types. 

So, what's your thinking here? Thanks!

**Comment by leaanthony** [comment]
They aren't necessary but do make it visually closer to standard Go types. As they are type aliases there is no performance hit. They are also optional.

**Comment by leaanthony** [comment]
Closing this for now. Let me know if you have any other questions 👍
